sudo: required
services:
    - docker

before_install:
    - docker build -t auotila/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true auotila/react-test npm test

after_success:
    - docker build -t auotila/multi-client ./client
    - docker build -t auotila/multi-nginx ./nginx
    - docker build -t auotila/multi-server ./server
    - docker build -t auotila/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub
    - docker push auotila/multi-client
    - docker push auotila/multi-worker
    - docker push auotila/multi-nginx
    - docker push auotila/multi-server

deploy:
    provider: elasticbeanstalk
    region: eu-north-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-north-1-771896602560
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


#deploy:
#   edge: true
#   provider: elasticbeanstalk
